# 帧流式关键词检测 - 简化配置示例
# Frame Streaming KWS - Simple Configuration Example
#
# 这是一个简化的配置，适合快速开始

dataset_conf:
    # 数据过滤
    filter_conf:
        max_length: 2048
        min_length: 0
    
    # 重采样到16kHz
    resample_conf:
        resample_rate: 16000
    
    speed_perturb: false
    
    # Fbank特征提取
    feats_type: 'fbank'
    feature_extraction_conf:
        feature_type: 'fbank'
        num_mel_bins: 80
        frame_shift: 10      # 10ms帧移
        frame_length: 25     # 25ms帧长
        dither: 1.0
    
    # 上下文扩展（帧流式必需）
    context_expansion: true
    context_expansion_conf:
        left: 2
        right: 2
    
    # 帧下采样
    frame_skip: 3
    
    # 数据增强
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 1
        num_f_mask: 1
        max_t: 20
        max_f: 10
    
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    
    batch_conf:
        batch_size: 256

model:
    input_dim: 400           # 80 * (2+1+2) = 400
    hidden_dim: 128
    preprocessing:
        type: none
    backbone:
        type: fsmn
        input_affine_dim: 140
        num_layers: 4
        linear_dim: 250
        proj_dim: 128
        left_order: 10
        right_order: 2
        left_stride: 1
        right_stride: 1
        output_affine_dim: 140
    classifier:
        type: identity
    activation:
        type: identity

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.0001

training_config:
    grad_clip: 5
    max_epoch: 80
    log_interval: 10
    criterion: ctc

